HFM Expanded/decisions/Peru-Bolivia Confederation.txt

Update to Peru-Bolivia. Includes a merging of Chilean decisions.

Update Peru-Bolivia Confederation.txt

---

README.md

Fixing the ReadMe so people can actually know how to install the mod. Hopefully this will help people.

Fixing the ReadMe

---

HFM Expanded/decisions/FlavourMod_FRA.txt

The decision was completely broken previously. This fixes it, but doesn't create an alliance with the PLC. For some reason it doesn't work, and I didn't want to put the time into figuring it out

Fix Create Poland-Lithuania decision

---

GFM/history/pops/1836.1.1/Albania.txt
GFM/localisation/cultures and religions.csv

Thanks for all the great work on the mod! These are just two tiny things that annoyed me.

Fixed a noculture pop and two cultures without localization

---

GFM/decisions/MiniMod-HUN #cleared.txt

Set the country flag so the decision actually disappears when taken and Hungary can't spam it for infinite prestige.

Fixed Croatian-Hungarian Settlement

---

Music Sub Mod.mod

I'd also like to add more music and some country flavor music but am unsure about the licensing implications

add user_dir = "Music Sub Mod" so the mod actually loads

---

Music Sub Mod.mod

Adding `user_dir = "Music Sub Mod"` caused the game to cache GFM assets in a new folder "Music Sub Mod_GFM" in \Documents\Paradox Interactive\Victoria II. This means savegames will be there also. Sorry! You can copy them to the GFM folder and continue playing.
The music mod still loads but it only repeats a few songs. I don't know what the problem is there. Maybe too many songs.

Oops. Remove user_dir

---

GFM/common/countries/Egypt.txt
GFM/common/cultures.txt

(example: Ahmed instead of Ahmet, Mohamed instead of Mehmet}

unturkified and added some names to the Misri Cutlure

---

GFM/decisions/Persia.txt

This is a small fix for some missing provinces in the Greater Persia decision. Note that I took some small creative liberties when reconnecting disconnected cores, e.g. in Turkmenia and Baluchistan.

fixed Greater Persia cores

---

GFM/events/URUFlavor.txt
GFM/localisation/000_Dukecza_SouthAmerica.csv
README.md

The Revolution of the lances event for UwUguay, plz abe check to see if i did an erling

My first event :blush:

---

GFM/history/countries/AMA - Amazonie.txt

So assuming that France is Catholic why don't add this religion to the ex-colony?

Missing Religion in Amazonie

---

GFM 1830/events/1830_GFM_BRZ.txt
GFM 1830/events/1830_GFM_TUR.txt

- double qutoes
- "ruling_party_ideology", not "ideology"
now hopefully github formatting doesnt screw me over..

fix 2 typos in gfm 1830

---

GFM/common/cb_types.txt

i am pretty sure it needs a corresponding `owner = { ai = no }`

testing for ai of a province? - cb_types.txt

---

GFM/events/PORFlavor.txt

audax validator was warning but they were silenced 😔

Declaring war on a province scope? - Update PORFlavor.txt

---

GFM/events/FlavourMod_USA.txt

the event is about horace mann doing some revolutionary shit regarding school systems
ok so this event would be awkward if we already had advanced school systems
in fact, degrading to "basic school" system would be very weird if you were already advanced by then
[given the context of the event]

Do not trigger mr. horace ideas if we already implemented them - FlavourMod_USA.txt

---

GFM/history/countries/AWS - Awsa.txt
GFM/history/countries/GON - Gonder.txt
GFM/history/countries/SHW - Shewa.txt
GFM/history/countries/TIG - Tigray.txt

military_reform -> foreign_training

---

GFM/events/FlavourMod_USA.txt

social_reform -> school_reforms (correct trigger, oops)

---

GFM/events/diplomatic annexation.txt

- ai factor doesnt matter on single option events
- sphere_owner will not execute with no sphere owner (also prereq of event already ensures we ALWAYS have a sphere owner)
- optimise small loops so like, it doesnt iterate more than it should

Small optimisations

---

GFM/decisions/renaming.txt
GFM/localisation/0000_IranRework.csv

long story short Dogubayazit is the name of the town built around 1934 after OG Bayazit got destroyed during 1930 ararat rebellion

more accurate bayazit name

---

GFM/decisions/FlavourMod_LIT.txt
GFM/decisions/Irredentism.txt

Since the decision can be taken by Lithuania, I added some cores Lithuania is missing to the Greater Belarus decision

Small fix to big belarus decision

---

GFM/decisions/Poland.txt
GFM/events/ENGFlavor.txt
GFM/events/South America.txt
GFM/events/V2ME Renaming (GFM).txt

- Trinidad and Gambia Fixes
- Removed cores from buying Tobago
- Fixes Gambia Purchase Loc
- Gambian rename taken from Gambian Purchase to Renaming file (Please check if I did it right, thanks)
- UBD and Latvia can into Gambia and Carribean

UBD Colonial 

---

GFM/decisions/1830_GFM_EGY.txt
GFM/decisions/NET.txt
GFM/decisions/RUS.txt
GFM/events/ChinaEvents.txt
GFM/events/FrenchNaturalBorders.txt
GFM/events/RUSFlavor.txt
GFM/events/morecultures.txt

PA has a checker it runs when loading the mod, these are fixes based on the errors detected by the checker

Fixes, based on Project Alice
